### ISSUE TITLE
Create data analysis to present to class

### ISSUE THREAD

**Issue by AKashton** [Arthurgamer1/Prickly-Port-Pirates-#7]
We need data to visualize and display for our presentation. Perhaps we can measure speeds on the amount of time it takes to add chats to a block and then link up into the chain.

**Comment by Arthurgamer1** [comment]
Ashton and I implemented a solution to get the data into a CSV file to then run a separate file for generating a data graph to test to be able to identify the runtime of the blockchain algorithm as it grows.
